swingerman/lovelace-fluid-level-background-card

src/fliud-meter.ts, src/fluid-background.ts, src/fluid-level-background-card.ts
Stop resize/render if the card is not visisble
=> fix(resize): improve size change detection

package.json, rollup.config.dev.js, src/fluid-background.ts, src/fluid-level-background-card.ts
- added theme based rounded corners
- hid overflow content
- removed bottom gap
fixes #50
=> fix: rounded corners with no overflow

.devcontainer/devcontainer.json, src/fliud-meter.ts, src/fluid-background.ts, src/fluid-level-background-card.ts
Uses the current theme's background color and dynamically updates if dark mode changes
=> feat: follows theme background color

src/fluid-background.ts, src/fluid-meter/fliud-meter.ts, src/fluid-meter/fluid-meter.interface.ts
=> feat: enables bubbles on value increase

.devcontainer/configuration.yaml, .devcontainer/ui-lovelace.yaml, .vscode/settings.json, src/editor.ts, src/fliud-meter.ts, src/fluid-background.ts, src/fluid-level-background-card.ts, src/localize/languages/en.json, src/types.ts, src/utils/theme-parser.ts
- arrange editor options into tabs
- add option to change card
- add option to set entity for filling state
Fixes #15
=> feat: arranges editor options into tabs

README.md, src/const.ts, src/editor.ts, src/fliud-meter.ts, src/fluid-background.ts, src/fluid-level-background-card.ts, src/fluid-meter.interface.ts, src/localize/languages/en.json, src/types.ts, src/utils/color.ts
=> feat: allows setting level color

src/fluid-level-background-card.ts
=> fix: uses and modifies theme shadow style

src/editor.ts, src/fluid-level-background-card.ts
=> feat: enbales bare minimum action editor

README.md, src/localize/languages/sv.json, src/localize/localize.ts
I fixed some typos in the read me file and provided a Swedish translation.
=> Fixed typos in read me and provided a Swedish translation

package-lock.json
Reverts swingerman/lovelace-fluid-level-background-card#174
=> Revert "build(npm): fixes lock file related build issue"

package-lock.json, package.json
Reverts swingerman/lovelace-fluid-level-background-card#299
=> Revert "build(deps-dev): bump typescript from 5.1.6 to 5.2.2"

src/editor.ts
=> Small typo "Choose a differnt card"

package-lock.json, rollup.config.dev.js, rollup.config.js, src/.lintstagedrc, src/fliud-meter.ts, src/fluid-background.ts, src/fluid-level-background-card.ts
=> fix(render): uses canvas height for fluid level calculation

src/fluid-background.ts, src/fluid-level-background-card.ts
=> fix(styles): removes extra border and shadow

README.md, src/const.ts, src/editor.ts, src/fliud-meter.ts, src/fluid-background.ts, src/fluid-level-background-card.ts, src/fluid-meter.interface.ts, src/localize/languages/en.json, src/localize/languages/hu.json, src/localize/languages/ptbr.json, src/localize/languages/ptpt.json, src/localize/languages/sv.json, src/localize/localize.ts, src/types.ts, src/utils/color.ts, src/utils/theme-parser.ts
=> feat: allows customizing the background color

.vscode/settings.json, src/editor.ts, src/localize/languages/en.json, src/localize/languages/hu.json, src/localize/languages/nb.json, src/localize/languages/ptbr.json, src/localize/languages/ptpt.json, src/localize/languages/sv.json
=> chore(localization): translate use theme color label

src/const.ts, src/editor.ts, src/fluid-background.ts, src/fluid-level-background-card.ts, src/localize/languages/en.json, src/localize/languages/hu.json, src/localize/languages/nb.json, src/localize/languages/ptbr.json, src/localize/languages/ptpt.json, src/localize/languages/sv.json, src/types.ts
=> feat: adds support for setting the full value

package-lock.json, src/action-handler-directive.ts, src/fluid-background.ts
=> chore: migrates deprecated lit imports

src/editor.ts, src/fluid-level-background-card.ts, src/lovelace-types.ts, src/types.ts
=> fix: moves child card render to the renderer method

src/fluid-level-background-card.ts
Uses createCardElement provided by Lovelace in order to create child cards.
refs: #291
=> fix: uses built in lovelace card creator method

package.json
=> chore(npm): bump version

package.json, src/const.ts, src/fluid-level-background-card.ts
=> chore: pulls card version from package

README.md, src/fliud-meter.ts
=> feat: supports alpha channel for color configuration

src/fluid-background.ts
=> fix: enures alpha channel always aplied if available

package.json
=> chore: set proper version

package-lock.json, src/.eslintrc, src/fluid-level-background-card.ts
=> fix: updates card if child card's entiy or entities state changes  #522

README.md, src/editor.ts, src/fliud-meter.ts, src/fluid-background.ts, src/fluid-level-background-card.ts, src/fluid-meter.interface.ts, src/localize/languages/en.json, src/localize/languages/hu.json, src/localize/languages/nb.json, src/localize/languages/ptbr.json, src/localize/languages/ptpt.json, src/localize/languages/sk.json, src/localize/languages/sv.json, src/types.ts
=> feat: enables randomly delay rendering
